- name: installing and starting httpd
  hosts: web
  become: yes
  tasks:
  - name: stopping nginx
    ansible.builtin.service:
      name: nginx
      state: stopped
      enabled: no
  - name: installing httpd
    ansible.builtin.package:
      name: httpd
      state: present
  - name: starting httpd
    ansible.builtin.service:
      name: httpd
      state: started