- name: this is play1
  host: local
  connection: local
  tasks:
  - name: play1 and task1
    ansible.builtin.debug:
      msg: "hi from play-1"

- name: this is play2
  hosts: web
  become: yes
  tasks:
  - name: play2 and task2
    ansible.builtin.package:
      msg: "hi from play-2"