- name: variables
  hosts: local
  connection: local
  vars:
    my_name: santhosh
    company: accenture
    role: devops engineer
  tasks:
  - name: course details
    ansible.builtin.debug:
      msg: "my name is {{my_name}}, working in {{company}} as a {{role}}"
  
  - name: my details
    vars:
      role: dba
    ansible.builtin.debug:
      msg: "my name is {{my_name}} was worked as {{role}} in {{company}}"
