- name: varibales from promt
  hosts: local
  connection: local
  vars_promt:
  - name: course
    promt: please enter course name
    private: yes #confidentail data
  - name: duration
    promt: please enter duration of the course
  - name: trainer
    promt: please enter trainer name
  tasks:
  - name: course info
    ansible.builtin.debug:
      msg: "course name is {{course}}, duration is {{duration}} and trainer name is {{trainer}}"