- name: varibales from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: course
    prompt: please enter course name
    private: yes #confidentail data
  - name: duration
    prompt: please enter duration of the course
  - name: trainer
    prompt: please enter trainer name
  tasks:
  - name: course info
    ansible.builtin.debug:
      msg: "course name is {{course}}, duration is {{duration}} and trainer name is {{trainer}}"