- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - vars.yml
  tasks:
  - name: course info
    ansible.builtin.debug:
      msg: "hello i am learning {{course}}, duration is {{duration}} and trainer is {{trainer}}"