- name: variables
  hosts: local
  connection: local
  vars:
    greet: "play"
  vars_files:
  - vars.yml
  vars_prompt:
  - name: greet
    prompt: please enter the value
    private: false
  tasks:
  vars:
    greet: task
  - name: print the variable
    ansible.builtin.debug:
      msg: "hello from {{greet}}"