- name: condtions
  hosts: local
  connection: local
  vars:
    my_number= 15
  tasks:
  - name: check the number
    ansible.buitlin.debug:
      msg: " {{my_number}} is  greater than 10"
    when: my_number > 10