- name: loops
  hosts: local
  connection: local
  tasks:
  - name: installing multiple tools
    ansible.builtin.package:
      name: "{{item}}"
      state: present
      
    loop:
    - mysql
    - gcc
    - httpd