- name: loops
  hosts: local
  connection: local
  tasks:
  - name: installing multiple tools
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: 'git', state: 'present'}
    - {  name: 'nginx', state: 'present'}
  

# - name: install packages
#   hosts: local
#   connection: local
#   tasks:
#   - name: install packages
#     ansible.builtin.package:
#       name: "{{ item.name }}"
#       state: "{{ item.state }}"
#     loop:
#     - { name: 'git', state: 'present'}
#     # - { name: 'mysql', state: 'absent'}
#     - { name: 'zip', state: 'present'}
#     # - { name: 'zip', state: 'absent'}