- name: functions
  hosts: local
  connection: local
  vars:
    course:
      course_name: devops
      trainer: siva
  tasks:
  - name: convert map to list
    ansible.builtin.debug:
     msg: " course info {{course | dict2items}}"
    
  - name: convert lower to upper
    vars:
      name: "santhosh kumar datti"
    ansible.builtin.debug:
      msg: "my name is {{name | upper}}"

  - name: convert upper to lower
    vars:
      name: "SANTHOSH KUMAR DATTI"
    ansible.builtin.debug:
      msg: "hello my name is {{name | lower}}"

  - name: print min and max number
    vars:
     numbers: [100,200,300,500]
    ansible.builtin.debug:
      msg: "small number is {{numbers | min}} big number is {{numbers | max}}"

  - name: ip address is correct or not
    vars:
      ip: "23.40.30.10" #wrong ip
    ansible.builtin.debug:
      msg: "{{ip | ansible.utils.ipaddr}}"