- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    # ansible.builtin.command: ls -ltr > /tmp/out.txt
    ansible.builtin.shell: ls -ltr > /tmp/out.txt