- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    # ansible.builtin.command: ls -ltr > /tmp/out.txt
    ansible.builtin.shell: ls -ltr > /tmp/out.txt

  - name: execute ls command in command module
    ansible.builtin.command: ls -ltr
    register: out_put

  - name: print the output
    ansible.builtin.debug:
      msg: "{{out_put}}"