- name: creating ec2 instances and route53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0ba4f7d960faeea7c #we can get under networking in the ec2 instance
    ami_id: ami-09c813fb71547fc4f #we can get under details in the ec2 instance
    sg_id: sg-099006b33a88c1e68
    instance_type: t2.micro
    zone: santhoshdatti.online
    instances: 
    - mysql
    - backend
    - frontend
  tasks:
  - name: installing python libraries
    ansible.builtin.pip:
      name: "{{item}}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{item}}"
      subnet_id: "{{subnet_id}}"
      image_id: "{{ami_id}}"
      security_group: "{{sg_id}}"
      instance_type: "{{instance_type}}"
    loop: "{{instances}}"
    register: ec2_info
